apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: nginx
        image: ghcr.io/${{ github.repository }}/alpine:${{ github.sha }}  # Usa il tag giusto qui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
