apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/cuccurese2010/nginx:latest  # ghcr.io e' il registry su github dove e' depositata l'immagine
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-secret  # Questo secret e' stato creato nei secret di Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
