name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_push:
    runs-on: self-hosted  # Usa il runner self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        sudo docker build -t ghcr.io/${{ github.repository }}/my-nginx:${{ github.sha }} .

    - name: Push Docker image
      run: |
        sudo docker push ghcr.io/${{ github.repository }}/my-nginx:${{ github.sha }}

  deploy:
    needs: build_and_push
    runs-on: self-hosted  # Usa il runner self-hosted per il deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/${{ github.repository }}/my-nginx:${{ github.sha }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
EOF
