name: Deploy to Kubernetes v1

on:
  push:
    branches:
      - main
    paths:
      - 'docker/Dockerfile'  # Percorso del Dockerfile
      - '.github/workflows/deploy.yml' # Percorso del file per il workflows
      - 'docker/deployment.yml'  # Percorso del file che effettua il deploy su kubernetes 

jobs:
  build_and_push:
    runs-on: self-hosted  # Usa il runner self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin # Effettua la login sul registy Github
      
    - name: Build Docker image
      run: |
             sudo docker build -t ghcr.io/cuccurese2010/nginx:latest ./docker  # Crea la build dal Dockerfile

    - name: Push Docker image
      run: |
             sudo docker push ghcr.io/cuccurese2010/nginx:latest # Fa il push della build nel registry

  deploy:
    needs: build_and_push
    runs-on: self-hosted  # Usa il runner self-hosted per il deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./docker/deployment.yml  # Qui viene lanciato il file per il deploy su kubernetes
