name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'
      - 'deployment.yml'  # Aggiunto per monitorare i cambiamenti nel file di deployment

jobs:
  build_and_push:
    runs-on: self-hosted  # Usa il runner self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: |
             docker login --username cuccurese2010 --password-stdin ${{ secrets.CR_PAT }} ghcr.io

    - name: Build Docker image
      run: |
             docker build .  --tag ghcr.io/cuccurese2010/github-runner/nginx:latest

    - name: Push Docker image
      run: |
             docker push ghcr.io/cuccurese2010/github-runner/nginx:latest

  deploy:
    needs: build_and_push
    runs-on: self-hosted  # Usa il runner self-hosted per il deploy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
